/**
 * Interface labels that belong to the Open template's chrome (navigation, landmarks,
 * reading aids). Product claims never live here: page copy comes from ../content.
 */
export const OPEN_COPY = {
  skip: "Skip to content",
  home: (brand: string) => `${brand} home`,
  tagline: "Live chat for websites. Every conversation starts in the corner.",
  nav: {
    main: "Main",
    open: "Open menu",
    close: "Close menu",
    sheet: "Site menu",
    viewAll: { products: "View all products", solutions: "View all solutions" },
  },
  footer: {
    label: "Footer",
    email: "Email",
    phone: "Phone",
    follow: "Follow",
    social: (name: string) => `${name} (opens in a new tab)`,
    top: "Back to top",
  },
  legal: {
    eyebrow: "Legal",
    contents: "Contents",
    sections: (n: number) => `${n} sections`,
  },
  help: { contact: "Contact", faq: "FAQ", write: "Write to us" },
  sla: { commitments: "Commitments", credits: "Credits" },
  contact: {
    panelSub: "We reply by email",
    details: "Details",
    support: "Support",
    loading: "Loading…",
  },
  blog: {
    filter: "Filter by category",
    results: (n: number) => `${n} ${n === 1 ? "article" : "articles"}`,
    pagination: "Pagination",
    resetSearch: "Show all articles",
    author: "Author",
    published: "Published",
    reading: "Reading time",
    category: "Category",
  },
  notFound: { status: "Status · away" },
  placeholder: "This section is coming together.",
  /** Labels inside illustrations of the product UI (no claims: those come from ../content). */
  mock: {
    hero: (brand: string) => `The ${brand} chat panel, open in the corner of a website`,
    inbox: (brand: string) => `The ${brand} inbox with recent conversations`,
    app: (name: string) => `${name}: the inbox and an open conversation`,
    call: "A video call in the browser, inside the chat widget",
    today: "Today",
    powered: "Powered by",
    composer: "Write a message…",
    videoCall: "Video call",
    join: "Join",
    inboxTitle: "Inbox",
    views: ["Open", "Pending", "Resolved"],
    savedReplies: "Type / for saved replies",
    read: "Read",
    online: "Online",
  },
  about: { values: "What we stand for", team: "Team" },
  pricing: {
    period: "Billing period",
    toman: "Prices in Toman",
    plans: "Plans",
    compare: "Comparison",
    questions: "Sales",
    current: "Your current plan",
    more: (n: number) => `${n} more`,
  },
  catalog: {
    breadcrumb: "Breadcrumb",
    home: "Home",
    items: (n: number, kind: "product" | "solution") =>
      `${String(n).padStart(2, "0")} ${kind === "product" ? (n === 1 ? "product" : "products") : n === 1 ? "solution" : "solutions"}`,
    overview: "Overview",
    related: "Related",
    next: "Next step",
  },
  download: {
    stores: "Stores",
    apps: "Apps",
    perks: "Why the apps",
    gallery: (name: string) => `${name} screenshots`,
    preview: "Preview",
    platform: "Platform",
  },
} as const;
