/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAutoblogRouteImport } from './routes/admin.autoblog'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminGeneralRouteImport } from './routes/admin.general'
import { Route as AdminLoginsRouteImport } from './routes/admin.logins'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as TagSlugRouteImport } from './routes/tag.$slug'
import { Route as ApiPublicAutoblogCronRouteImport } from './routes/api/public/autoblog-cron'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutoblogRoute = AdminAutoblogRouteImport.update({
  id: '/autoblog',
  path: '/autoblog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeneralRoute = AdminGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginsRoute = AdminLoginsRouteImport.update({
  id: '/logins',
  path: '/logins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutoblogCronRoute = ApiPublicAutoblogCronRouteImport.update({
  id: '/api/public/autoblog-cron',
  path: '/api/public/autoblog-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/api-docs': typeof ApiDocsRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/autoblog': typeof AdminAutoblogRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/logins': typeof AdminLoginsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/tags': typeof AdminTagsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/autoblog-cron': typeof ApiPublicAutoblogCronRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/api-docs': typeof ApiDocsRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/autoblog': typeof AdminAutoblogRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/logins': typeof AdminLoginsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/tags': typeof AdminTagsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/autoblog-cron': typeof ApiPublicAutoblogCronRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/api-docs': typeof ApiDocsRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/terms': typeof TermsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/autoblog': typeof AdminAutoblogRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/logins': typeof AdminLoginsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/tags': typeof AdminTagsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/autoblog-cron': typeof ApiPublicAutoblogCronRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/api-docs'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sla'
    | '/terms'
    | '/admin/ai'
    | '/admin/autoblog'
    | '/admin/backup'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/general'
    | '/admin/logins'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/tags'
    | '/blog/$slug'
    | '/tag/$slug'
    | '/admin/'
    | '/blog/'
    | '/api/public/autoblog-cron'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/api-docs'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sla'
    | '/terms'
    | '/admin/ai'
    | '/admin/autoblog'
    | '/admin/backup'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/general'
    | '/admin/logins'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/tags'
    | '/blog/$slug'
    | '/tag/$slug'
    | '/admin'
    | '/blog'
    | '/api/public/autoblog-cron'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/api-docs'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sla'
    | '/terms'
    | '/admin/ai'
    | '/admin/autoblog'
    | '/admin/backup'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/general'
    | '/admin/logins'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/tags'
    | '/blog/$slug'
    | '/tag/$slug'
    | '/admin/'
    | '/blog/'
    | '/api/public/autoblog-cron'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlaRoute: typeof SlaRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  TagSlugRoute: typeof TagSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicAutoblogCronRoute: typeof ApiPublicAutoblogCronRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/autoblog': {
      id: '/admin/autoblog'
      path: '/autoblog'
      fullPath: '/admin/autoblog'
      preLoaderRoute: typeof AdminAutoblogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/general': {
      id: '/admin/general'
      path: '/general'
      fullPath: '/admin/general'
      preLoaderRoute: typeof AdminGeneralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logins': {
      id: '/admin/logins'
      path: '/logins'
      fullPath: '/admin/logins'
      preLoaderRoute: typeof AdminLoginsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autoblog-cron': {
      id: '/api/public/autoblog-cron'
      path: '/api/public/autoblog-cron'
      fullPath: '/api/public/autoblog-cron'
      preLoaderRoute: typeof ApiPublicAutoblogCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAutoblogRoute: typeof AdminAutoblogRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminGeneralRoute: typeof AdminGeneralRoute
  AdminLoginsRoute: typeof AdminLoginsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAutoblogRoute: AdminAutoblogRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminChatRoute: AdminChatRoute,
  AdminGeneralRoute: AdminGeneralRoute,
  AdminLoginsRoute: AdminLoginsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiDocsRoute: ApiDocsRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlaRoute: SlaRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  TagSlugRoute: TagSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicAutoblogCronRoute: ApiPublicAutoblogCronRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
